<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<script src="<c:url value="/resources/js/libs/DataTables/datatables.min.js" />"></script>
<script src="<c:url value="/resources/js/libs/DataTables/sorting/numeric-dots.js" />"></script>
<script src="<c:url value="/resources/js/libs/DataTables/sorting/date-euro.js" />"></script>
<script src="<c:url value="/resources/js/libs/DataTables/dataRender/ellipsis.js" />"></script>
<script src="<c:url value="/resources/js/libs/select2.js" />"></script>
<script src="<c:url value="/resources/js/libs/pdfjs/build/pdf.js" />"></script>
<script src="<c:url value="/resources/js/libs/pdfjs/build/pdf.worker.js" />"></script>
<script src="<c:url value="/resources/js/libs/pdfobject.js" />"></script>
<script src="<c:url value="/resources/js/libs/underscore-min.js" />"></script>

<%-- <script src="<c:url value="/resources/js/libs/jquery.bootstrap-growl.js" />"></script> --%>
<script src="<c:url value="/resources/template/simpliq/js/fullcalendar.min.js" />"></script>
<script src="<c:url value="/resources/js/libs/nouislider/nouislider.js" />"></script>
<script src="<c:url value="/resources/js/libs/nouislider/wNumb.js" />"></script>
<script src="<c:url value="/resources/js/libs/timepicker/jquery.timepicker.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/excanvas.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.flot.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.flot.pie.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.flot.stack.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.flot.resize.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.flot.time.js" />"></script>

<script src="<c:url value="/resources/template/simpliq/js/jquery.chosen.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.uniform.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.cleditor.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.noty.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.elfinder.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.raty.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.iphone.toggle.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.uploadify-3.1.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.gritter.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.imagesloaded.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.masonry.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.knob.modified.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.sparkline.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/counter.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/raphael.2.1.0.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/justgage.1.0.1.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.autosize.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/retina.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/jquery.placeholder.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/wizard.min.js" />"></script>
<script src="<c:url value="/resources/template/simpliq/js/charts.min.js" />"></script>
